services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_PASSWORD: password
      MYSQL_USER: appdb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql
  ###< doctrine/doctrine-bundle ###
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
